.TH QOTDD 8 2016-01-29 "qotd 0.9" "System Manager's Manual"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.SH NAME
qotdd \- A daemon to provide an interesting quote every day.
.SH SYNOPSIS
.P
qotdd [\fIOPTION\fP]...
.P
qotdd [\fB\-\-help\fP | \fB\-\-version\fP]
.SH DESCRIPTION
QOTD (quote of the day) is specified in RFC 865 as a way of broadcasting a quote to users. On both TCP and UDP, port 17 is officially reserved for this purpose. \fBqotdd\fP(8) is meant to provide a simple QOTD daemon on IPv4 and/or IPv6 on either TCP or UDP.
.P
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-f\fP, \fB\-\-foreground\fP
Do not fork, but run in the foreground.
.TP
\fB\-c\fP, \fB\-\-config\fP \fIconfig\-file\fP
Specify an alternate configuration file location. The default is at `\fI/etc/qotd.conf\fP'. (Overrides a previous \fB\-c\fP or \fB\-N\fP option)
.TP
\fB\-N\fP, \fB\-\-noconfig\fP
Do not read from a configuration file, but use the default options instead. (Overrides a previous \fB\-c\fP option)
.TP
\fB\-\-lax\fP
Disable strict configuration parsing. Without this option, the daemon will perform security checks on input files. Be aware that using this option makes the program vulnerable to confused deputy attacks.
.TP
For more information on the following three options, see \fBqotd.conf\fP(5):
.TP
\fB\-P\fP, \fB\-\-pidfile\fP \fIpidfile\fP
Override the pidfile name given in the configuration file with the given file instead.
.TP
\fB\-s\fP, \fB\-\-quotes\fP \fIquotes\-file\fP
Override the quotes file given in the configuration file with the given file instead.
.TP
\fB\-j\fP, \fB\-\-journal\fP \fIjournal\-file\fP
Overrides the journal file given in the configuration file with the given file instead.
.TP
\fB\-4\fP, \fB\-\-ipv4\fP
Only listen on IPv4. The default behavior is to listen on both IPv4 and IPv6.
.TP
\fB\-6\fP, \fB\-\-ipv6\fP
Only listen on IPv6.
.TP
\fB\-t\fP, \fB\-\-tcp\fP
Use TCP instead of UDP. This is the default behavior.
.TP
\fB\-u\fP, \fB\-\-udp\fP
Use UDP instead of TCP. (Not fully implemented yet)
.TP
\fB\-q\fP, \fB\-\-quiet\fP
Only output error messages. This is the same as using `\fB\-\-journal\fP \fI/dev/null\fP'.
.TP
.BR \-\-help
List all options and what they do.
.TP
.BR \-\-version
Print the version and some basic license information.
.SH RETURN CODES
\fBqotdd\fP has the following return codes:
.TP
.BR 0
success
.TP
.BR 1
general error
.TP
.BR 17
invalid arguments
.TP
.BR 18
invalid configuration file or settings
.TP
.BR 19
failed a security check
.TP
.BR 20
out of memory
.TP
.BR 21
I/O or network error
.TP
.BR 22
\fISIGSEGV\fP or \fISIGINT\fP killed the process
.TP
.BR 23
internal error
.SH SEE ALSO
.TP
\fBqotd.conf\fP(5), \fBtelnet\fP(1), \fBnetcat\fP(1)
.SH AUTHOR
.TP
Ammon Smith (ammon.i.smith@gmail.com)
